name: hoodie_w_a_boogie
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  email_validator: ^2.1.17

  google_maps_flutter: ^2.3.0
  google_maps_flutter_android: ^2.4.15

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
