name: hoodie_w_a_boogie
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  email_validator: ^2.1.17

  google_maps_flutter: ^2.3.0
  google_maps_flutter_android: ^2.4.15

  cupertino_icons: ^1.0.2
  lottie: ^2.0.0
  fab_circular_menu: ^1.0.0
  flip_card:
  flutter_riverpod: ^2.3.6 
  http:
  dartz:
  flutter_polyline_points:
  flutter_rating_stars:


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animassets/mapanimation.json
    # - assets/mapicons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: WorkSans
  #     fonts:
  #       - asset: assets/fonts/WorkSans-Regular.ttf
  #       - asset: assets/fonts/WorkSans-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/WorkSans-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/WorkSans-SemiBold.ttf
  #         weight: 500
  #       - asset: assets/fonts/WorkSans-Light.ttf
  #         weight: 200
  #       - asset: assets/fonts/WorkSans-Thin.ttf
  #         weight: 300
  #       - asset: assets/fonts/WorkSans-Medium.ttf
  #         weight: 400
  #       - asset: assets/fonts/WorkSans-ExtraLight.ttf
  #         weight: 100
  # 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
